language: node_js

node_js:
    - node

services:
    - docker
    
# by default it will do the below so we can comment it out
# install:
#     - npm ci

before_install:
    - docker build -t abc1 -f Dockerfile.dev .

script:
    - docker run abc1 npm run test:unit -- --coverage

after_success:
    - npm run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN_VUE_TRAVIS  
    keep_history: true,
    local_dir: dist
    on:
        branch: master